### ISSUE TITLE
The country's numeric representation should be the same as the international phone number identifier

### ISSUE THREAD

**Issue by Hygor** [Yummygum/svelte-flagpack#2]
## The problem
The actual numeric representation doesn't have any meaning to exist. It does not represent anything from the country, neither the flag.

## The solution
By changing the numeric representation to the actual international phone number identifier, like that one with the letters, will a meaning for that number representation, and also could be easier integrate with telephone libraries.

## Example

for the England it should be: 
`<Flag code='EN | ENG | 044 ' />`

for Italy it should be:
`<Flag code='IT | ITA | 039' />`

for Brazil it should be:
`<Flag code='BR | BRA | 055' />`

...and so on!

**Comment by daoneandonly** [comment]
Hi @Hygor, thanks for thinking along with Flagpack. Our numeric value comes from the [ISO 3166 standard](https://en.wikipedia.org/wiki/ISO_3166). If you wish to lookup what numeric value represents which country, I'd like to direct you to our [Flag Index page](https://flagpack.xyz/docs/flag-index/) on the Flagpack website. All three values we use for flags are derived from this standard and we'll be using this for the time to come. We have no current plans to include country calling codes to Flagpack.
